"""expand_farmer_farm_scheme_add_notifications_need_info

Revision ID: 5f04273eaf53
Revises: e76e81eea1df
Create Date: 2026-07-07 15:12:50.087496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f04273eaf53'
down_revision: Union[str, Sequence[str], None] = 'e76e81eea1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extend the ApplicationStatus enum with new values
    op.execute("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'need_info'")
    op.execute("ALTER TYPE applicationstatus ADD VALUE IF NOT EXISTS 'under_verification'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('farmers', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('farmers', sa.Column('category', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('taluka', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('education', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('farmer_type', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('land_ownership', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'farmers', ['pan_number'])
    op.add_column('farms', sa.Column('farm_name', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('survey_number', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('cultivable_area', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('soil_ph', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('secondary_crop', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('crop_category', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('season', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('organic_farming', sa.Boolean(), nullable=True))
    op.add_column('farms', sa.Column('fertilizer_usage', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('livestock', sa.String(), nullable=True))
    op.alter_column('farms', 'land_area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('subsidy_applications', sa.Column('inspection_status', sa.String(), nullable=True))
    op.add_column('subsidy_applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('subsidy_applications', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('subsidy_schemes', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subsidy_schemes', sa.Column('max_beneficiaries', sa.Integer(), nullable=True))
    op.add_column('subsidy_schemes', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('subsidy_schemes', sa.Column('scheme_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsidy_schemes', 'scheme_documents')
    op.drop_column('subsidy_schemes', 'banner_url')
    op.drop_column('subsidy_schemes', 'max_beneficiaries')
    op.drop_column('subsidy_schemes', 'application_deadline')
    op.alter_column('subsidy_applications', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('subsidy_applications', 'updated_at')
    op.drop_column('subsidy_applications', 'inspection_status')
    op.alter_column('farms', 'land_area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('farms', 'livestock')
    op.drop_column('farms', 'fertilizer_usage')
    op.drop_column('farms', 'organic_farming')
    op.drop_column('farms', 'longitude')
    op.drop_column('farms', 'latitude')
    op.drop_column('farms', 'season')
    op.drop_column('farms', 'crop_category')
    op.drop_column('farms', 'secondary_crop')
    op.drop_column('farms', 'soil_ph')
    op.drop_column('farms', 'cultivable_area')
    op.drop_column('farms', 'survey_number')
    op.drop_column('farms', 'farm_name')
    op.drop_constraint(None, 'farmers', type_='unique')
    op.drop_column('farmers', 'land_ownership')
    op.drop_column('farmers', 'farmer_type')
    op.drop_column('farmers', 'occupation')
    op.drop_column('farmers', 'education')
    op.drop_column('farmers', 'ifsc_code')
    op.drop_column('farmers', 'bank_account_number')
    op.drop_column('farmers', 'taluka')
    op.drop_column('farmers', 'category')
    op.drop_column('farmers', 'date_of_birth')
    op.drop_column('farmers', 'gender')
    op.drop_column('farmers', 'father_name')
    op.drop_column('farmers', 'pan_number')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
