"""add phone_number

Revision ID: 9cfa37dd82ca
Revises: 5f04273eaf53
Create Date: 2026-07-08 15:12:35.435669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfa37dd82ca'
down_revision: Union[str, Sequence[str], None] = '5f04273eaf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'address')
    op.drop_column('farmers', 'phone_number')
    # ### end Alembic commands ###
