"""Add new fields for scheme eligibility

Revision ID: e76e81eea1df
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-07 04:31:39.028348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76e81eea1df'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('annual_income', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('irrigation_type', sa.String(), nullable=True))
    op.add_column('farms', sa.Column('crop_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'crop_type')
    op.drop_column('farms', 'irrigation_type')
    op.drop_column('farmers', 'annual_income')
    # ### end Alembic commands ###
